name: Open Edison CI Setup
description: Checkout, install UV, and sync dependencies (Python version from pyproject.toml)

inputs:
  uv-version:
    description: UV version to install
    required: false
    default: 'latest'

runs:
  using: composite
  steps:
    - name: Install UV
      uses: astral-sh/setup-uv@v4
      with:
        version: ${{ inputs.uv-version }}

    - name: Sync dependencies
      shell: bash
      run: uv sync

