name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run CI
        run: make ci

