name: Dead Code (Vulture)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/workflows/**'

jobs:
  vulture:
    if: github.event_name == 'pull_request' || github.event.pull_request == null
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Vulture
        run: make deadcode

