name: Dead Code (Vulture) [legacy]

on:
  # Replaced by CI (grouped). Keep manual trigger only.
  workflow_dispatch:

jobs:
  vulture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Vulture
        run: make deadcode

