name: Package build test (macos)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  test-package-build-macos:
    if: github.event_name == 'pull_request' || github.event.pull_request == null
    strategy:
      matrix:
        os: [macos-15, macos-14, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Open Edison
        uses: ./.github/actions/setup

      - name: Build package
        run: make build_package

      - name: Test package build with uvx
        run: |
          cd /
          uvx --refresh --from "${{ github.workspace }}/" open-edison --help

