name: Package build test (ubuntu amd64)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  test-package-build-ubuntu:
    if: github.event_name == 'pull_request' || github.event.pull_request == null
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Open Edison
        uses: ./.github/actions/setup

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Build package
        run: make build_package

      - name: Test package build with uvx
        run: |
          cd /
          uvx --refresh --from "${{ github.workspace }}/" open-edison --help

