name: Type Check (Ty) [legacy]

on:
  # Replaced by CI (grouped). Keep manual trigger only.
  workflow_dispatch:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Ty
        run: uv run ty check .

