name: Version Guard

on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch main for comparison
        run: |
          git fetch origin main:refs/remotes/origin/main --depth=1

      - name: Run version guard
        run: make check_higher_than_main

